### ISSUE TITLE
Pocketspinx demo application waits infinitly

### ISSUE THREAD

**Issue by jkriba** [matrix-io/matrix-creator-pocketsphinx#3]
Hi,
 Kindly help me with the below issue,
When i was trying to run the pocketspinx demo , the application is getting into an infinite wait state [i.e. Ready state] and does not respond to any of my voice commands.

I have followed exact steps provided in the documentation mentioned and also extracted the language models too..

am i missing something here...pls help..

Below is the logs,
INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
INFO: acmod.c(162): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/share/pocketsphinx/model/en-us/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/share/pocketsphinx/model/en-us/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(149): Reading HMM transition probability matrices: /usr/local/share/pocketsphinx/model/en-us/en-us/transition_matrices
INFO: acmod.c(113): Attempting to use PTM computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/share/pocketsphinx/model/en-us/en-us/means
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/share/pocketsphinx/model/en-us/en-us/variances
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(304): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/share/pocketsphinx/model/en-us/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(838): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 4123 * 20 bytes (80 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: assets/6706.dic
INFO: dict.c(213): Dictionary size 22, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(336): 22 words read
INFO: dict.c(358): Reading filler dictionary: /usr/local/share/pocketsphinx/model/en-us/en-us/noisedict
INFO: dict.c(213): Dictionary size 27, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 21336 bytes (20 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 21336 bytes (20 KiB) for single-phone word triphones
INFO: kws_search.c(406): KWS(beam: -1080, plp: -23, default threshold -450, delay 10)
INFO: ngram_model_trie.c(354): Trying to read LM in trie binary format
INFO: ngram_model_trie.c(365): Header doesn't match
INFO: ngram_model_trie.c(177): Trying to read LM in arpa format
INFO: ngram_model_trie.c(193): LM of order 3
INFO: ngram_model_trie.c(195): #1-grams: 21
INFO: ngram_model_trie.c(195): #2-grams: 39
INFO: ngram_model_trie.c(195): #3-grams: 39
INFO: lm_trie.c(474): Training quantizer
INFO: lm_trie.c(482): Building LM trie
INFO: ngram_search_fwdtree.c(74): Initializing search tree
INFO: ngram_search_fwdtree.c(101): 20 unique initial diphones
INFO: ngram_search_fwdtree.c(186): Creating search channels
INFO: ngram_search_fwdtree.c(323): Max nonroot chan increased to 175
INFO: ngram_search_fwdtree.c(333): Created 20 root, 47 non-root channels, 5 single-phone words
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
INFO: kws_search.c(448): TOTAL kws 0.00 CPU nan xRT
INFO: kws_search.c(451): TOTAL kws 0.00 wall nan xRT
INFO: pocketsphinx_demo.cpp(223): ./pocketsphinx_demo COMPILED ON: May 18 2017, AT: 12:13:05

INFO: pocketsphinx_demo.cpp(165): Ready....

**Comment by jkriba** [comment]
Hi,
  I am really struggling for making the PocketSpinx demo getting worked out for the last 2 weeks.
I was really fed up with the product, and the level of documentation we have.

I am a research scholar and I was recommending my organization to buy bulk orders of Matrix voice for their Smart Campus project and was trying to do a PoC with this Pocketspinx..

But if this is not working, i need to look for another Mic Array product to serve my purpose, please help, thanks

Regards
JK

**Comment by kdpatino** [comment]
Hello @jkriba ,

We apologize for the late response.  Now, we released a bunch of features of the Microphone support. Now you could use the microphone array as a Linux device (Kernel Module).

We already update this repository and the steps in the README.

Let me know if you have any other question.

Best Regards,

Kevin Patino

**Comment by prtdomingo** [comment]
Hey @kdpatino,

Is there anything I should change on the setup based on the new release of features? I'm still experiencing the same issue mentioned above. 

Are there any steps or documentation I can check for common issues encountered for this?

Thanks,
Philip
